"""
General domain — the original domain-agnostic behaviour.

It supplies no fixed ontology, so the pipeline generates the schema and the
agent panel from the brief with the LLM, exactly as before the domain
abstraction was introduced. This is the default for every new project.
"""

from __future__ import annotations

from quorum_backend.domains.base import DomainProfile

GENERAL_DOMAIN = DomainProfile(
    key="general",
    name="General reasoning",
    description=(
        "Domain-agnostic. The ontology and the agent panel are generated by "
        "the LLM for each brief. Use this for strategy, policy, research, or "
        "any topic without a dedicated domain."
    ),
    fixed_ontology=None,
)
