'use client'

import Link from 'next/link'
import {
  ArrowRight,
  ArrowUpRight,
  BrainCircuit,
  GitBranch,
  MessagesSquare,
  Sparkles,
  Workflow,
  Bot,
  Briefcase,
  Building2,
  Scale,
  FlaskConical,
  HelpCircle,
  FileText,
  Upload,
  ScrollText,
  Layers,
} from 'lucide-react'
import { motion, useReducedMotion, type Variants } from 'framer-motion'

import SiteHeader from '@/components/site/site-header'
import SiteFooter from '@/components/site/site-footer'
import QuorumMark from '@/components/site/quorum-mark'

// ============================================
// Animation primitives
// ============================================

const fadeUp: Variants = {
  hidden: { opacity: 0, y: 24 },
  visible: {
    opacity: 1,
    y: 0,
    transition: { duration: 0.6, ease: [0.16, 1, 0.3, 1] },
  },
}

const fadeIn: Variants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: { duration: 0.5, ease: 'easeOut' },
  },
}

const staggerContainer: Variants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: { staggerChildren: 0.08, delayChildren: 0.05 },
  },
}

const staggerItem: Variants = {
  hidden: { opacity: 0, y: 16 },
  visible: {
    opacity: 1,
    y: 0,
    transition: { duration: 0.5, ease: [0.16, 1, 0.3, 1] },
  },
}

// ============================================
// Capabilities — 6 cards reflecting the full pipeline
// ============================================
const capabilities = [
  {
    title: 'Reality-seed documents',
    description:
      'Upload PDFs, markdown, or plain text. Quorum extracts the content and uses it as the ground truth for ontology + graph generation.',
    icon: Upload,
  },
  {
    title: 'Topic-aware ontologies',
    description:
      'No predefined schema. The LLM designs an entity + edge type schema specific to your brief, then extracts every concrete entity from the seed.',
    icon: BrainCircuit,
  },
  {
    title: 'Live knowledge graphs',
    description:
      'Force-directed d3 visualization. Drag nodes, toggle edge labels, click to drill into the rich entity profile.',
    icon: GitBranch,
  },
  {
    title: 'Dynamic agent personas',
    description:
      'One agent per real-world entity. Each persona has age, MBTI, country, profession, expertise, bias, and stance — all LLM-designed for the topic.',
    icon: MessagesSquare,
  },
  {
    title: 'Time-stepped simulation',
    description:
      'Per-agent activity profiles, hour-of-day weighting, dual-platform recommendation algorithms, narrative orchestration, and round-by-round debate.',
    icon: Layers,
  },
  {
    title: 'Prediction reports',
    description:
      'A senior-analyst LLM plans an outline of the simulation findings, then writes each section using the debate transcript as evidence. Download as Markdown.',
    icon: ScrollText,
  },
]

// ============================================
// 7-stage pipeline
// ============================================
const pipelineStages = [
  {
    n: '01',
    title: 'Ontology Generation',
    description:
      'LLM designs a topic-specific entity + edge type schema from your brief and uploaded seeds.',
  },
  {
    n: '02',
    title: 'GraphRAG Build',
    description:
      'Extracts every concrete entity and relation from the brief, validated against the ontology.',
  },
  {
    n: '03',
    title: 'Environment Setup',
    description:
      'One LLM-designed persona per real-world entity, with bio, MBTI, expertise, and stance.',
  },
  {
    n: '04',
    title: 'Generate Config',
    description:
      'Time + per-agent activity + platform recommendation algorithms generated by the LLM.',
  },
  {
    n: '05',
    title: 'Initial Activation',
    description:
      'Narrative direction, hot topics, and a starter post sequence to seed the simulation.',
  },
  {
    n: '06',
    title: 'Run Simulation',
    description:
      'Round-by-round debate where agents reason in character about the brief.',
  },
  {
    n: '07',
    title: 'Generate Report',
    description:
      'A multi-section markdown report planned and written from the simulation findings.',
  },
]

// ============================================
// Use cases
// ============================================
const useCases = [
  {
    icon: Briefcase,
    label: 'Strategy',
    title: 'Should we ship this in Q2?',
    body:
      'Upload your roadmap PDF, write the question, and watch a panel of stakeholders — risk officers, founders, engineers, customer advocates — debate the trade-offs before they bite you in standup.',
  },
  {
    icon: Building2,
    label: 'Hiring',
    title: 'Senior PM or two mid-level engineers?',
    body:
      'Quorum extracts every relevant entity from your hiring doc — open roles, budget, team — and instantiates one agent per stakeholder perspective. Each weighs the decision through their own bias.',
  },
  {
    icon: Scale,
    label: 'Policy',
    title: 'Will this regulation hold up?',
    body:
      'Upload the draft, let Quorum extract every concrete actor it touches — agencies, courts, advocacy groups, affected communities — and surface the constituencies that will resist and why.',
  },
  {
    icon: FlaskConical,
    label: 'Research',
    title: 'Stress-test a thesis before publishing.',
    body:
      'Upload your draft. Quorum casts a panel of expert critics — domain specialists, statisticians, methodological skeptics — and each one challenges the work from their own discipline.',
  },
]

// ============================================
// FAQ
// ============================================
const faqs = [
  {
    q: 'How is this different from a single LLM with multiple "personas"?',
    a: 'A single LLM playing roles converges on its own bias — every persona ends up sounding the same. Quorum gives each agent its own system prompt, persona vector, and stance derived from a real entity in your knowledge graph, then explicitly tracks disagreements across rounds. The dissents matter as much as the agreement.',
  },
  {
    q: 'Where does the agent panel come from? Is it hardcoded?',
    a: 'No. The pipeline runs an LLM-driven ontology generator that designs an entity schema for your specific brief, then extracts real entities from the brief and any uploaded documents. Each speaker-capable entity becomes one agent with an LLM-designed persona — age, MBTI, country, profession, bias, the works. Different briefs produce different panels.',
  },
  {
    q: 'What kind of files can I upload?',
    a: 'PDF, Markdown, and plain text. Up to 5 files per project, 8 MB each. The text is extracted with pypdf and fed into the ontology generator + graph builder so the schema is grounded in the actual document content rather than just your brief.',
  },
  {
    q: 'Do I need an OpenAI key?',
    a: 'No. Quorum supports Google Gemini (free tier), Anthropic Claude (paid), and Azure AI Foundry (Kimi K2.5 and others). The LLM layer is provider-agnostic — switching is one env var.',
  },
  {
    q: 'How big can the graph get?',
    a: 'The current in-memory graph builder is bounded to ~40 nodes and ~60 edges per simulation, which keeps each LLM call under the token budget. For larger graphs you can swap in a hosted graph backend behind the same GraphBuilder interface.',
  },
  {
    q: 'What does the report look like?',
    a: 'A 2-5 section Markdown document. The planner LLM designs an outline from the simulation findings, then a section-writer LLM writes each section using the debate transcript and agent profiles as evidence. Direct quotes from agents appear as blockquotes. You can download the full report as a .md file.',
  },
  {
    q: 'What happens if the LLM hits a content filter?',
    a: 'Quorum catches the content filter error, logs it to the system dashboard, and the affected agent skips its turn cleanly. The simulation continues with the remaining agents. You\'ll see exactly which agent was blocked and why.',
  },
]

// ============================================
// Stack strip
// ============================================
const integrations = [
  'Google Gemini',
  'Azure / Kimi K2.5',
  'Claude API',
  'Next.js 14',
  'FastAPI',
  'd3-force',
  'pypdf',
  'NetworkX',
]

// ============================================
// Main page
// ============================================
export default function LandingPage() {
  const reduceMotion = useReducedMotion()
  // When the user has prefers-reduced-motion, drop straight to visible
  // (no transitions, no scroll triggers).
  const initialState = reduceMotion ? 'visible' : 'hidden'

  return (
    <main className="min-h-screen flex flex-col bg-[var(--bg)]">
      <SiteHeader />

      {/* ============================================
          Hero
          ============================================ */}
      <section className="relative overflow-hidden">
        <div className="container-2xl pt-16 pb-24 lg:pt-24 lg:pb-32">
          <div className="grid lg:grid-cols-[1.2fr_1fr] gap-12 lg:gap-16 items-center">
            <motion.div
              initial={initialState}
              animate="visible"
              variants={staggerContainer}
            >
              <motion.div
                variants={staggerItem}
                className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-[var(--brand-soft)] border border-[var(--brand)]/20"
              >
                <Sparkles className="h-3.5 w-3.5 text-[var(--brand)]" />
                <span className="text-xs font-medium text-[var(--brand)]">
                  7-stage multi-agent reasoning pipeline
                </span>
              </motion.div>

              <motion.h1
                variants={staggerItem}
                className="h1 mt-6 text-[var(--ink)]"
              >
                Upload a doc. Spawn a{' '}
                <span className="brand-pill">swarm</span>. Get a report.
              </motion.h1>

              <motion.p
                variants={staggerItem}
                className="mt-6 max-w-xl text-lg leading-relaxed text-[var(--muted)]"
              >
                Quorum reads your reality-seed PDFs, designs a topic-specific
                ontology, instantiates one AI agent per real-world entity, runs
                them through a structured debate, and writes you a prediction
                report — all locally, with the LLM provider of your choice.
              </motion.p>

              <motion.div
                variants={staggerItem}
                className="mt-8 flex flex-wrap gap-3"
              >
                <Link href="/workspace" className="btn btn-primary btn-lg">
                  Launch workspace
                  <ArrowRight className="h-4 w-4" />
                </Link>
                <Link href="/docs" className="btn btn-ghost btn-lg">
                  Read the docs
                  <Workflow className="h-4 w-4" />
                </Link>
              </motion.div>

              <motion.div
                variants={staggerItem}
                className="mt-12 grid grid-cols-3 gap-6 max-w-md"
              >
                <div>
                  <p className="font-display text-3xl font-medium text-[var(--ink)]">7</p>
                  <p className="mt-1 text-xs text-[var(--muted)]">Pipeline stages</p>
                </div>
                <div>
                  <p className="font-display text-3xl font-medium text-[var(--ink)]">∞</p>
                  <p className="mt-1 text-xs text-[var(--muted)]">Domains supported</p>
                </div>
                <div>
                  <p className="font-display text-3xl font-medium text-[var(--ink)]">100%</p>
                  <p className="mt-1 text-xs text-[var(--muted)]">Self-hostable</p>
                </div>
              </motion.div>
            </motion.div>

            <motion.div
              initial={reduceMotion ? { opacity: 1, scale: 1 } : { opacity: 0, scale: 0.95, y: 12 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              transition={{ duration: 0.7, delay: 0.15, ease: [0.16, 1, 0.3, 1] }}
            >
              <HeroPreview />
            </motion.div>
          </div>
        </div>

        <div className="absolute inset-x-0 bottom-0 h-32 bg-gradient-to-t from-[var(--bg-soft)] to-transparent pointer-events-none" />
      </section>

      {/* ============================================
          Stack strip
          ============================================ */}
      <RevealSection className="border-y border-[var(--line)] bg-[var(--bg-soft)]">
        <div className="container-2xl py-12">
          <p className="label-mono text-center mb-8">Powered by an open stack</p>
          <motion.div
            variants={staggerContainer}
            initial={initialState}
            whileInView="visible"
            viewport={{ once: true, amount: 0.4 }}
            className="flex flex-wrap items-center justify-center gap-x-10 gap-y-4"
          >
            {integrations.map((name) => (
              <motion.span
                key={name}
                variants={staggerItem}
                className="text-sm font-medium text-[var(--muted)] hover:text-[var(--ink)] transition-colors"
              >
                {name}
              </motion.span>
            ))}
          </motion.div>
        </div>
      </RevealSection>

      {/* ============================================
          Capabilities
          ============================================ */}
      <RevealSection id="capabilities" className="section">
        <div className="container-2xl">
          <SectionHeading
            label="Capabilities"
            heading={
              <>
                Built for <span className="brand-pill">production reasoning</span>.
              </>
            }
            description="Everything you need to deploy multi-agent systems that actually work in real decision contexts — including your own documents."
          />

          <motion.div
            variants={staggerContainer}
            initial={initialState}
            whileInView="visible"
            viewport={{ once: true, amount: 0.15 }}
            className="mt-14 grid gap-px bg-[var(--line)] border border-[var(--line)] rounded-lg overflow-hidden md:grid-cols-2 lg:grid-cols-3"
          >
            {capabilities.map((item) => {
              const Icon = item.icon
              return (
                <motion.div
                  key={item.title}
                  variants={staggerItem}
                  className="bg-[var(--card)] p-8 transition-colors hover:bg-[var(--brand-tint)] group"
                >
                  <div className="inline-flex h-10 w-10 items-center justify-center rounded-md bg-[var(--bg-soft)] group-hover:bg-[var(--brand-soft)] transition-colors">
                    <Icon className="h-5 w-5 text-[var(--ink)] group-hover:text-[var(--brand)] transition-colors" />
                  </div>
                  <h3 className="mt-5 font-display text-xl font-medium tracking-tight text-[var(--ink)]">
                    {item.title}
                  </h3>
                  <p className="mt-3 text-sm leading-relaxed text-[var(--muted)]">
                    {item.description}
                  </p>
                </motion.div>
              )
            })}
          </motion.div>
        </div>
      </RevealSection>

      {/* ============================================
          Pipeline — 7 numbered cards
          ============================================ */}
      <RevealSection
        id="workflow"
        className="section bg-[var(--bg-soft)] border-y border-[var(--line)]"
      >
        <div className="container-2xl">
          <SectionHeading
            label="The pipeline"
            heading={
              <>
                Seven stages from <span className="brand-pill">brief</span> to
                report.
              </>
            }
            description="Each stage is a discrete LLM call you can inspect, replay, or skip. The whole pipeline runs in under a minute on Gemini Flash."
          />

          <motion.div
            variants={staggerContainer}
            initial={initialState}
            whileInView="visible"
            viewport={{ once: true, amount: 0.15 }}
            className="mt-14 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"
          >
            {pipelineStages.map((stage) => (
              <motion.div
                key={stage.n}
                variants={staggerItem}
                whileHover={{ y: -3, transition: { duration: 0.2 } }}
                className="card p-5 hover:bg-[var(--card-hover)] hover:border-[var(--brand)] transition-colors"
              >
                <div className="flex items-baseline justify-between">
                  <span className="font-mono text-xs font-medium text-[var(--brand)]">
                    {stage.n}
                  </span>
                  <ArrowRight className="h-3 w-3 text-[var(--muted)]" />
                </div>
                <h3 className="mt-4 font-display text-base font-medium text-[var(--ink)]">
                  {stage.title}
                </h3>
                <p className="mt-2 text-xs leading-relaxed text-[var(--muted)]">
                  {stage.description}
                </p>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </RevealSection>

      {/* ============================================
          Use cases
          ============================================ */}
      <RevealSection className="section">
        <div className="container-2xl">
          <SectionHeading
            label="Use cases"
            heading={
              <>
                For decisions that <span className="brand-pill">need pushback</span>.
              </>
            }
            description="Anywhere you'd benefit from a panel of skeptical experts before you commit, Quorum gives you one in seconds — informed by your actual documents."
          />

          <motion.div
            variants={staggerContainer}
            initial={initialState}
            whileInView="visible"
            viewport={{ once: true, amount: 0.15 }}
            className="mt-14 grid gap-4 md:grid-cols-2"
          >
            {useCases.map((uc) => {
              const Icon = uc.icon
              return (
                <motion.div
                  key={uc.title}
                  variants={staggerItem}
                  whileHover={{ y: -3, transition: { duration: 0.2 } }}
                  className="card p-6 hover:border-[var(--brand)] transition-colors"
                >
                  <div className="flex items-center gap-2 mb-3">
                    <Icon className="h-3.5 w-3.5 text-[var(--brand)]" />
                    <span className="label-mono">{uc.label}</span>
                  </div>
                  <h3 className="font-display text-xl font-medium text-[var(--ink)] tracking-tight">
                    {uc.title}
                  </h3>
                  <p className="mt-3 text-sm text-[var(--muted)] leading-relaxed">
                    {uc.body}
                  </p>
                </motion.div>
              )
            })}
          </motion.div>
        </div>
      </RevealSection>

      {/* ============================================
          Code preview — quick start
          ============================================ */}
      <RevealSection className="section bg-[var(--bg-soft)] border-y border-[var(--line)]">
        <div className="container-2xl">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <motion.div
              variants={fadeUp}
              initial={initialState}
              whileInView="visible"
              viewport={{ once: true, amount: 0.3 }}
            >
              <p className="label-mono">Quick start</p>
              <h2 className="h2 mt-4 text-[var(--ink)]">
                A few <span className="brand-pill">curl</span> calls.
              </h2>
              <p className="mt-5 text-lg text-[var(--muted)]">
                The backend exposes a clean REST API for the whole pipeline.
                Upload your doc, build the graph, run the simulation, generate
                the report.
              </p>
              <div className="mt-8 flex gap-3">
                <Link href="/workspace" className="btn btn-primary">
                  Try it now
                  <ArrowRight className="h-4 w-4" />
                </Link>
                <Link href="/docs/api-reference" className="btn btn-ghost">
                  API reference
                  <ArrowUpRight className="h-4 w-4" />
                </Link>
              </div>
            </motion.div>
            <motion.div
              variants={fadeUp}
              initial={initialState}
              whileInView="visible"
              viewport={{ once: true, amount: 0.3 }}
              transition={{ delay: 0.1 }}
              className="code-block"
            >
              <div className="flex items-center justify-between mb-4 pb-3 border-b border-[var(--brand)]/30">
                <span className="text-xs font-mono text-[var(--brand)]">
                  Quorum REST API
                </span>
                <span className="text-xs font-mono text-[var(--muted)]">200 OK</span>
              </div>
              <pre className="text-xs whitespace-pre-wrap">
{`# 1. Create the project
curl -X POST localhost:8000/api/projects \\
  -d '{"brief": "Should we adopt Aurora over PostgreSQL?"}'

# 2. Upload reality-seed PDFs
curl -X POST localhost:8000/api/projects/proj_X/upload \\
  -F "file=@architecture-review.pdf"

# 3. Generate ontology + graph
curl -X POST localhost:8000/api/projects/proj_X/graph/ontology/generate
curl -X POST localhost:8000/api/projects/proj_X/graph/build

# 4. Spawn agents + simulation config
curl -X POST localhost:8000/api/projects/proj_X/env/setup
curl -X POST localhost:8000/api/projects/proj_X/simulation/prepare

# 5. Generate activation
curl -X POST localhost:8000/api/projects/proj_X/simulation/activate

# 6. Run the debate
curl -X POST localhost:8000/api/projects/proj_X/simulation/start

# 7. Generate the prediction report
curl -X POST localhost:8000/api/projects/proj_X/report/generate
→ { "report": { "title": "...", "sections": [...], "markdown": "..." } }`}
              </pre>
            </motion.div>
          </div>
        </div>
      </RevealSection>

      {/* ============================================
          FAQ
          ============================================ */}
      <RevealSection className="section">
        <div className="container-2xl">
          <SectionHeading
            label="FAQ"
            heading={
              <>
                Common <span className="brand-pill">questions</span>.
              </>
            }
          />

          <motion.div
            variants={staggerContainer}
            initial={initialState}
            whileInView="visible"
            viewport={{ once: true, amount: 0.1 }}
            className="mt-12 max-w-3xl space-y-3"
          >
            {faqs.map((f, i) => (
              <motion.details
                key={i}
                variants={staggerItem}
                className="group bg-[var(--card)] border border-[var(--line)] rounded-md overflow-hidden hover:border-[var(--line-strong)] transition-colors"
              >
                <summary className="cursor-pointer flex items-center gap-3 px-5 py-4 list-none">
                  <HelpCircle className="h-3.5 w-3.5 text-[var(--brand)] flex-shrink-0" />
                  <span className="text-sm font-medium text-[var(--ink)] flex-1">
                    {f.q}
                  </span>
                  <span className="text-[var(--muted)] font-mono text-sm group-open:rotate-180 transition-transform">
                    ⌄
                  </span>
                </summary>
                <div className="px-5 pb-4 pt-1 ml-7">
                  <p className="text-sm text-[var(--muted)] leading-relaxed">{f.a}</p>
                </div>
              </motion.details>
            ))}
          </motion.div>
        </div>
      </RevealSection>

      {/* ============================================
          CTA
          ============================================ */}
      <RevealSection className="section">
        <div className="container-2xl">
          <motion.div
            variants={fadeUp}
            initial={initialState}
            whileInView="visible"
            viewport={{ once: true, amount: 0.3 }}
            className="card p-12 lg:p-20 text-center bg-[var(--card)] border border-[var(--line)]"
          >
            <motion.div
              initial={reduceMotion ? { scale: 1, opacity: 1 } : { scale: 0.6, opacity: 0 }}
              whileInView={{ scale: 1, opacity: 1 }}
              viewport={{ once: true }}
              transition={{ type: 'spring', stiffness: 200, damping: 18, delay: 0.1 }}
              className="inline-flex text-[var(--brand)] mb-6"
            >
              <QuorumMark size={48} />
            </motion.div>
            <h2 className="h2 text-[var(--ink)]">
              Ready to <span className="brand-pill">convene</span>?
            </h2>
            <p className="mt-5 text-lg text-[var(--muted)] max-w-xl mx-auto">
              Launch the workspace, upload a doc, type your topic, and watch
              the swarm debate it in real time. No setup, no signup.
            </p>
            <div className="mt-8 flex flex-wrap gap-3 justify-center">
              <Link href="/workspace" className="btn btn-primary btn-lg">
                Start a simulation
                <ArrowRight className="h-4 w-4" />
              </Link>
              <Link href="/docs" className="btn btn-ghost btn-lg">
                Read the docs
              </Link>
            </div>
          </motion.div>
        </div>
      </RevealSection>

      <SiteFooter />
    </main>
  )
}

// ============================================
// Reusable: a section that fades up when it scrolls into view
// ============================================
function RevealSection({
  children,
  className = '',
  id,
}: {
  children: React.ReactNode
  className?: string
  id?: string
}) {
  const reduceMotion = useReducedMotion()
  return (
    <motion.section
      id={id}
      className={className}
      initial={reduceMotion ? 'visible' : 'hidden'}
      whileInView="visible"
      viewport={{ once: true, amount: 0.1 }}
      variants={fadeIn}
    >
      {children}
    </motion.section>
  )
}

// ============================================
// Reusable: section heading with label + h2 + description
// ============================================
function SectionHeading({
  label,
  heading,
  description,
}: {
  label: string
  heading: React.ReactNode
  description?: string
}) {
  const reduceMotion = useReducedMotion()
  return (
    <motion.div
      initial={reduceMotion ? 'visible' : 'hidden'}
      whileInView="visible"
      viewport={{ once: true, amount: 0.6 }}
      variants={staggerContainer}
      className="max-w-2xl"
    >
      <motion.p variants={staggerItem} className="label-mono">
        {label}
      </motion.p>
      <motion.h2
        variants={staggerItem}
        className="h2 mt-4 text-[var(--ink)]"
      >
        {heading}
      </motion.h2>
      {description && (
        <motion.p
          variants={staggerItem}
          className="mt-5 text-lg text-[var(--muted)]"
        >
          {description}
        </motion.p>
      )}
    </motion.div>
  )
}

// ============================================
// Hero preview component (animated)
// ============================================
function HeroPreview() {
  const reduceMotion = useReducedMotion()
  return (
    <div className="relative">
      <div className="card p-6 bg-[var(--card)] border border-[var(--line-strong)] shadow-lg">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2">
            <span className="h-2 w-2 rounded-full bg-[var(--brand)] pulse-dot" />
            <span className="font-mono text-[10px] uppercase tracking-wider text-[var(--muted)]">
              Live debate
            </span>
          </div>
          <span className="text-[10px] font-mono text-[var(--muted)]">Round 2 / 3</span>
        </div>

        {/* Reality seed pill */}
        <div className="mb-3 flex items-center gap-2 px-3 py-2 bg-[var(--bg-soft)] border border-[var(--line)] rounded-md">
          <FileText className="h-3 w-3 text-[var(--brand)] flex-shrink-0" />
          <span className="text-[11px] text-[var(--ink)] truncate flex-1">
            architecture-review.pdf
          </span>
          <span className="text-[10px] font-mono text-[var(--muted)]">8.2 KB</span>
        </div>

        <motion.div
          variants={staggerContainer}
          initial={reduceMotion ? 'visible' : 'hidden'}
          animate="visible"
          transition={{ delayChildren: 0.5 }}
          className="space-y-3"
        >
          <PreviewMessage
            agent="Risk Radar"
            color="var(--brand)"
            text="The compliance gap is the binding constraint. We need a phased rollout."
          />
          <PreviewMessage
            agent="Opportunity Scout"
            color="var(--accent-blue)"
            text="Agreed — but only if we keep the core MVP timeline intact."
          />
          <PreviewMessage
            agent="Systems Mapper"
            color="var(--accent-green)"
            text="Phase 1 dependencies are all in our control. Greenlight."
          />
        </motion.div>

        <div className="mt-5 pt-4 border-t border-[var(--line)] flex items-center justify-between">
          <div>
            <p className="text-[10px] font-mono uppercase text-[var(--muted)]">
              Consensus
            </p>
            <p className="text-sm font-medium text-[var(--ink)] mt-0.5">
              84% agreement
            </p>
          </div>
          <div className="flex -space-x-2">
            {[
              'var(--brand)',
              'var(--accent-blue)',
              'var(--accent-green)',
              'var(--accent-purple)',
            ].map((c, i) => (
              <span
                key={i}
                className="h-6 w-6 rounded-full border-2 border-[var(--card)]"
                style={{ background: c }}
              />
            ))}
          </div>
        </div>
      </div>

      {/* Floating accent card */}
      <motion.div
        initial={reduceMotion ? { opacity: 1, y: 0 } : { opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.7, duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
        className="absolute -bottom-6 -left-6 card p-4 bg-[var(--card)] border border-[var(--line-strong)] shadow-md hidden lg:block"
      >
        <div className="flex items-center gap-2 mb-1">
          <ScrollText className="h-3 w-3 text-[var(--brand)]" />
          <p className="text-[10px] font-mono uppercase text-[var(--muted)]">Report</p>
        </div>
        <p className="font-display text-sm font-medium text-[var(--ink)]">3 sections ready</p>
      </motion.div>
    </div>
  )
}

function PreviewMessage({
  agent,
  color,
  text,
}: {
  agent: string
  color: string
  text: string
}) {
  return (
    <motion.div
      variants={staggerItem}
      className="flex gap-3 p-3 rounded-md bg-[var(--bg-soft)]"
    >
      <span
        className="h-7 w-7 rounded-md flex-shrink-0 mt-0.5 inline-flex items-center justify-center"
        style={{ background: color }}
      >
        <Bot className="h-3.5 w-3.5 text-white" />
      </span>
      <div>
        <p className="text-[11px] font-mono font-medium text-[var(--ink)]">{agent}</p>
        <p className="text-xs text-[var(--muted)] mt-0.5 leading-relaxed">{text}</p>
      </div>
    </motion.div>
  )
}
